### ISSUE TITLE
Aztec Steam Slides, no blood sacrafices

### ISSUE THREAD

**Issue by TameOfGroans** [xloem/qrstream#1]
It would be great to also employ ISO 24778, Aztec, for streaming by slideshow.

**Comment by xloem** [comment]
I added support for receiving Aztec codes.  Sending them will have to wait until the encoding process migrates beyond the zxing android-integration library, which only encodes to QR code (and notably only does so as a slideshow).

**Comment by xloem** [comment]
Turns out there's an extra you can send to control the code format.  You can select Aztec Code from the settings now.
